### ISSUE TITLE
Compatibilité Atos 2

### ISSUE THREAD

**Issue by septoctobre** [mageho/Mageho_Atos#10]
Bonjour,

Une compatibilité avec Atos 2 est-elle prévue ?

Merci

**Comment by mageho** [comment]
Bonsoir,

C'est prévu pour le roadmap de notre magasin sur l'année prochaine.

Actuellement, nous tournons sur une version 1.9.3 avec énormément de modules tiers et de développement personnalisé.
Nous sommes sur un trimestre très active en flux ce qui nous bloque pour un changement de version.

Entre temps, nous regardons si un module voit le jour.

Bien à vous

**Comment by septoctobre** [comment]
C'est noté, merci pour votre retour.
