### ISSUE TITLE
No actual support for "authorize" mode (standard payment method) ?

### ISSUE THREAD

**Issue by goodluckrememberingthisone** [mageho/Mageho_Atos#12]
Hi,

Doing a few tests on a local site with the module in version 1.2.0.0 (config.xml), included in the site in novembre 2015, it seems the atos/atoswps/payment_action system.xml configuration variable does not really affect the capture_mode.

Looking at Mageho_Atos_Model_Method_Standard::_getCaptureMode() used to determine the value for capture_mode parameter in Mageho_Atos_Model_Method_Standard::callRequest() 
```
    /**
     * Get capture mode
     *
     * @return string
     */
    protected function _getCaptureMode()
    {
        return $this->getConfig()->getPaymentAction($this->getConfigData('capture_mode'));
    }
```
capture_mode does not exist in system.xml so a `$action=null` value is passed to getPaymentAction().

=> Even if Mage_Payment_Model_Method_Abstract::ACTION_AUTHORIZE / "Validation" is selected for atos/atoswps/payment_action in admin, Mageho_Atos_Model_Config::getPaymentAction()  will always default to Mage_Payment_Model_Method_Abstract::ACTION_AUTHORIZE_CAPTURE / "Author Capture".

```
    /*
     * Mapper from Atos/Sips Standard payment actions to Magento payment actions
     *
     * @return string|null
     */
    public function getPaymentAction($action)
    {
        switch ($action) {
            case Mage_Payment_Model_Method_Abstract::ACTION_AUTHORIZE:
                return self::PAYMENT_ACTION_AUTHORIZE;
            default:
            case Mage_Payment_Model_Method_Abstract::ACTION_AUTHORIZE_CAPTURE:
                return self::PAYMENT_ACTION_AUTHORIZE_CAPTURE;
        }
    }
```

The problematic code is still there in the master branch.

Regards,

**Comment by mageho** [comment]
Issue fixed : Correction: support for "authorize" mode
