### ISSUE TITLE
Paiement refused;Status Canceled;Item not returning in stock

### ISSUE THREAD

**Issue by ericnetconcepteurs** [mageho/Mageho_Atos#2]
Hi,

congratulations for this extension,

i configure atos when a paiement is not allowed by the bank: status canceled, it's ok but the product

not returns to stock,

is there a solution?

Best,

______________________________________________________________________

Bonjour,

Bravo pour ce module très simple à installer et fonctionnel, je le recommande vivement.

Voici ma question: 

J'ai configuré le module pour lorsqu'un paiement est refusé par la banque, le statut de celle-ci passe en "Annulé", cela se produit correctement mais le produit ne se réincrémente pas automatiquement dans le stock.

Y-at'il une solution à ce problème?

Cordialement,

**Comment by mageho** [comment]
Effectivement, c'est un problème que je rencontre sur mes installations aussi et qui peut vite faire perdre rapidement des commandes.
Je regarde.

**Comment by ericnetconcepteurs** [comment]
Ok,

merci pour votre retour,

tenez-moi informé,

Cordialement,

Le 26 janvier 2015 14:20, Ilan Parmentier <notifications@github.com> a
écrit :

> Effectivement, c'est un problème que je rencontre sur mes installations
> aussi et qui peut vite faire perdre rapidement des commandes.
> Je regarde.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mageho/Mageho_Atos/issues/2#issuecomment-71459251>.
>



-- 
*Eric MARCIANO*
*Agence Netconcepteurs*
*75 rue Carnot - 92300 LEVALLOIS PERRET*

Mobile          : 06 17 97 22 93
Website        : http://www.netconcepteurs.com/
Facebook     : http://www.facebook.com/netconcepteurs
Showreel      : http://youtu.be/MGcpuyH4mok

**Comment by mageho** [comment]
Problem fixed with commit 09fc21db4876cda44c1e7cc6856140418014f73b.
