### ISSUE TITLE
Multi-Website Configuration

### ISSUE THREAD

**Issue by azurams** [mageho/Mageho_Atos#5]
Hi,
I am developing a new Magento store with a multi website configuration.
site1.domain.tld / site2.domain.tld
In System > Config , when I switch to my second website context, fields like "Bin file to build request/reponse", and the "Generate Pathfile & Parcom Files" does not show at website level. I know that directive in etc/system.xml prevent that.
> show_in_website => 0

Is there any reason to this restriction. How could I generate parmcom and pathfile for my site2 website ?
I could copy lib/atos/* to lib/atos-site2/* and customise path and url, but when generating payment request, how to tell the module to use the files specific to "site 2" ?

Anyhelp would be welcomed.
I can explain my needs in french if needed.

**Comment by mageho** [comment]
Good morning,

Even if you have multiple website, with multiple bank account settings, especially merchant ID I mean, you just need the couple of binary files sent by your bank.

The module take care automatically of the configuration on a website level from the magento configuration and global variable from your store.

Through this has not been tested far, I didn't hear any problem at all.

If so, you are free to change the module on github.

Cheers
