### ISSUE TITLE
Wrong currency with HK dollar

### ISSUE THREAD

**Issue by tanvandinh** [mageho/Mageho_Atos#6]
When place order with Hongkong dollar the currency will change to default currency on Atos. 
Does Atos not allow currency Hongkong dollar ? If the answer is "yes" what is currency Atos support ? 
Thank for support.

**Comment by mageho** [comment]
Good morning, 

So far, our french platform support :

- Euro
- Dollar US
- Franc Suisse
- Livre Sterling
- Dollar Canadien
- Yen japonais
- Peso mexicain
- Ancienne lire turque
- Dollar australien
- Dollarnéo-zélandais
- Couronne norvégienne
- Cruzeiro Brésilien
- Peso argentin
- Riel Cambodge
- Dollarde Taiwan
- Couronne Danoise
- Couronne Suédoise
- Wonsud-coréen
- Dollarde Singapour

If you have heard of it support, you could had it in the config.xml file manually, with the iso code of the currency.

Cheers
