### ISSUE TITLE
paiement depuis l'admin

### ISSUE THREAD

**Issue by Jerome38** [mageho/Mageho_Atos#7]
Bonjour,

Nous avons parfois des commandes par téléphone que nous passons via le BO pour des soucis pratiques.
Le module atos ne semble pas gérer les commandes depuis l'interface d'administration. Est-il prévu d'ajouter cette fonctionnalité ?

Merci

**Comment by mageho** [comment]
Bonjour,

Nous-même e-commerçant, nous traitons ce genre de cas par le biais du TPE mercanet (solution BNP PARIBAS) back-office (vente VAD), c'est une option supplémentaire de votre package bancaire.

La gestion back-office n'a pas été implementée, car trop couteuse en temps, et par manque simple de motivation.

Bien à vous
