### ISSUE TITLE
Le client a quitté la page de paiement sans finaliser sa commande

### ISSUE THREAD

**Issue by jeffpils** [mageho/Mageho_Atos#8]
Bonjour,

J'ai ré-installé votre module de paiement (qui est vraiment super au demeurant) et je n'ai plus de validation de la commande, le status n'est pas le bon par contre la transaction est bien passée a la SGenerale. je n'arrive pas à trouver d'ou vient le problème. C'est gênant car il n'y à pas de mail envoyé au client et on doit tout checker à la main.

Pouvez vous m'aider ?

Merci d'avance.

JF Grimonnet

**Comment by mageho** [comment]
Bonjour,

Vraisemblablement, un problème sur le binaire de réponse, blocage par adresse IP du serveur de retour, ...

Je ne peux pas vous aider davantage.

Bien à vous
